version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    command:
      - bash
      - -c
      - |
        while ! nc -z zookeeper 2181; do sleep 1; done
        /etc/confluent/docker/run &
        while ! nc -z localhost 29092; do sleep 1; done
        kafka-topics --create --topic task1-1 --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        kafka-topics --create --topic task1-2 --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        kafka-topics --create --topic task2 --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        kafka-topics --create --topic task2-output --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        kafka-topics --create --topic task3-1 --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        kafka-topics --create --topic task3-2 --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        kafka-topics --create --topic task4 --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        kafka-topics --create --topic task4-output --bootstrap-server localhost:29092 --partitions 1 --replication-factor 1 --if-not-exists
        wait

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8070:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 
  